# Generated by Django 4.2.3 on 2023-08-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegrecords', '0003_farmer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmer',
            table='Farm',
        ),
    ]
