# Generated by Django 4.2.3 on 2023-08-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegrecords', '0004_alter_farmer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='veg',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vegrecords.veg'),
            preserve_default=False,
        ),
    ]
